//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_SPADevelopementEntities : DbContext
    {
        public DB_SPADevelopementEntities()
            : base("name=DB_SPADevelopementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<ClassTeacherAllocation> ClassTeacherAllocations { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<InstituteDetail> InstituteDetails { get; set; }
        public virtual DbSet<SubjectMaster> SubjectMasters { get; set; }
        public virtual DbSet<AcademicMaster> AcademicMasters { get; set; }
        public virtual DbSet<BloodGroup> BloodGroups { get; set; }
        public virtual DbSet<CasteMaster> CasteMasters { get; set; }
        public virtual DbSet<GenderMaster> GenderMasters { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<StudentClassMapping> StudentClassMappings { get; set; }
        public virtual DbSet<StudentMaster> StudentMasters { get; set; }
        public virtual DbSet<FeeHeadMaster> FeeHeadMasters { get; set; }
        public virtual DbSet<ReligionMaster> ReligionMasters { get; set; }
        public virtual DbSet<StudentFeeAllocationMaster> StudentFeeAllocationMasters { get; set; }
        public virtual DbSet<StudentFeeAllocation> StudentFeeAllocations { get; set; }
        public virtual DbSet<DepositThrough> DepositThroughs { get; set; }
        public virtual DbSet<StudentFeeDeposit> StudentFeeDeposits { get; set; }
    }
}
