//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentFeeDeposit
    {
        public int Id { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> HeadTypeId { get; set; }
        public Nullable<decimal> AmountDeposit { get; set; }
        public Nullable<decimal> AdditionalDiscount { get; set; }
        public string DiscountDescription { get; set; }
        public Nullable<int> DepositThrough { get; set; }
        public Nullable<int> DepositFor { get; set; }
        public int IsActive { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
