//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentFeeAllocationMaster
    {
        public int Id { get; set; }
        public int AllocationTypeId { get; set; }
        public int AllocationOn { get; set; }
        public int HeadTypeId { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> DiscountPercenatge { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public int IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpDatedDate { get; set; }
        public Nullable<int> FeeType { get; set; }
    }
}
