//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentMaster
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string RegistrationNumber { get; set; }
        public string RollNumber { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> BloodGroup { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> CastId { get; set; }
        public Nullable<int> ReligionId { get; set; }
        public string AdharCardNumber { get; set; }
        public string FatherPhone { get; set; }
        public string ContactPhone { get; set; }
        public string EmailId { get; set; }
        public int ClassId { get; set; }
        public int SectionId { get; set; }
        public string Adddress { get; set; }
        public int AcademicYear { get; set; }
        public int IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
